### ISSUE TITLE
Cannot open a file from commad line

### ISSUE THREAD

**Issue by VladimirMarkelov** [RMichelsen/Nvy#3]
Both releases works the same to me: in command line I move to a directory with source files and I type `d:\neovim\bin\nvy.exe file.txt`. Nvy opens with empty content. Trying to `:e TAB-TAB` shows me the list with `file.txt`, and I can open it.

**Comment by RMichelsen** [comment]
Ah yea, this is an oversight. I'll push a fix for this tomorrow.

**Comment by RMichelsen** [comment]
This should now work, I'm not entirely happy with the command-line parsing, but it should work unless you do some very exotic things I think.

**Comment by VladimirMarkelov** [comment]
Something still does not work. I have two copies of the data in `engine.c` and `engine.rs` 👍 

```
D:\neovim\bin>dir engine.*
09/24/2020  12:12 AM            16,433 engine.c
09/24/2020  12:12 AM            16,433 engine.rs
```

When I do `nvy.exe engine.c` - `nvy` opens the file. It works as expected. But the command `nvy.exe engine.rs` does nothing: neither nvy opens nor errors in console. I wonder why it dislikes `*.rs`. I tried opening text file `nvy.exe txt5.txt` and it works as well. But I cannot open any `*.rs` file that is just a text file.

**Comment by VladimirMarkelov** [comment]
@RMichelsen  I do not see a button "reopen" for the issue. So I only added a comment

**Comment by RMichelsen** [comment]
@VladimirMarkelov Hmm I can't seem to reproduce, I can open `.rs` files just fine, do you have the latest release [v0.1.2](https://github.com/RMichelsen/Nvy/releases/tag/v0.1.2)?

**Comment by VladimirMarkelov** [comment]
Yes,  I downloaded and replaced the old one. I think if I had not replaced, I would not be able to open `*.c` files from command line. I tried another `*.rs` file and it was not opened. I wonder how to help you debugging it.

Edit: I tried to build but my compiler does not support CXX20

**Comment by RMichelsen** [comment]
Hmm thats really odd. Do you have a debugger available if I send you a debug build with .exe and .pdb?

Edit: [Nvy.zip](https://github.com/RMichelsen/Nvy/files/5285019/Nvy.zip)

**Comment by VladimirMarkelov** [comment]
I managed to launch your debug version(had to download a few debug DLLs), but debug `nvy` does not start even without arguments. It fails at:

```
Assertion failed!

Program: D:\neovim\bin\Nvy.exe
File: ../src/renderer/renderer.cpp
Line: 32

Expression: ret == S_OK
```

In sources that I just got from github it is : 
```
31	WIN_CHECK(D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, flags, feature_levels,
32		ARRAYSIZE(feature_levels), D3D11_SDK_VERSION, &temp_device, &renderer->d3d_feature_level, &temp_context));
```

Extra information: Windows 10 64 bit.

**Comment by RMichelsen** [comment]
This definitely should not happen. I will need to look into adding some logging perhaps in case these sort of things are not reproducable for me. Could you join me on the neovim gitter https://gitter.im/neovim/neovim so we can debug together, if you have time?

**Comment by VladimirMarkelov** [comment]
OK. I logged in to gitter, but did not join the channel. What is next?

**Comment by RMichelsen** [comment]
If you join the neovim channel I'll private message you

**Comment by RMichelsen** [comment]
Check out the new release, [v0.1.2](https://github.com/RMichelsen/Nvy/releases/tag/v0.1.2). It should fix the issue on your end. It now parses the `init.vim` file to find the guifont setting so the correct size should be set when using `--geometry=` as well.

**Comment by VladimirMarkelov** [comment]
Thanks! It works great. The issue can be closed.
